### ISSUE TITLE
Plz do this plz

### ISSUE THREAD

**Issue by lincoln-bridge** [oopsie1412/alcebot#15]
When type a!muchlove make love has been given to @everyone

Plzzzzzzz thx so much u da best

**Comment by alecagayan** [comment]
Thank you for leaving your comment. Please wait up to 2 weeks for changes to take place. Your request will most likely be implemented in update 1.1.4 or 1.1.5

**Comment by 5731la** [comment]
Already implemented, please close

**Comment by lincoln-bridge** [comment]
Thanks
