### ISSUE TITLE
Support for HTCPCP

### ISSUE THREAD

**Issue by 5731la** [oopsie1412/alcebot#37]
Alcebot's lack of support for HTCPCP (and its extension, HTCPCP-TEA) is a major oversight and may break compatibility with an untold number of systems. I cannot see me or my organization adopting any technology with such a major oversight.

**Comment by 5731la** [comment]
this is activity now dont close

**Comment by 5731la** [comment]
fuck off stalebot

**Comment by 5731la** [comment]
Become fresh like a subway sandwich

**Comment by alecagayan** [comment]
no

**Comment by 5731la** [comment]
no
